version: '3'

services:
  web:
    container_name: fetch-rewards
    image: ml_text_similarity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always  # To enable automatic restart, other options are 'unless-stopped' or 'on-failure'
